#Two Random Numbers Generated by the Computer and Application Asking the User for the Result of the Operation
username=input("Enter your username=> ")
print("Welcome to the game {}.".format(username))
print("Easy Level:1","İntermediate Level:2","Hard level:3")
command="0"
print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
command=input("Command=> ")
while(command!="y" and command!="n"):
    print("You entered the wrong command. Re-enter the command.")
    print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
    command=input("Command=> ")
if(command=="n"):
    print("Game Over {}!".format(username))
counter1=0
counter2=0
counter3=0
counter4=0
counter5=0
counter6=0
while(command=="y") :
    level=int(input("Level=> "))
    while(level>3 or level<1):
        print("You have selected the wrong level. Select the level again.")
        level=int(input("Level=>"))
    print("Start the game {}!".format(username))
    from random import randint
    if(level==1):
        number1=randint(1,100)
        number2=randint(1,100)
        print("number1=",number1)
        print("number2=",number2)
        if number1<50:
            operation="-"
            result=number1-number2
        else :
            operation="+"
            result=number1+number2
        print("result=number1{}number2".format(operation))
        answer=int(input("result="))
        if(answer==result):
            print("+10 point")
            print("Congratulations {}, You know".format(username))
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter1+=1
        else : 
            print("-5 puan")
            print("Sorry {}, you didn't know. True Answer=".format(username),result)
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter2+=1
    if(level==2):
        number1=randint(1,100)
        number2=randint(1,100)
        print("number1=",number1)
        print("number2=",number2)
        if(number1<50):
            operation="*" 
            result=number1*number2
        else :
            operation="//"
            result=number1//number2
            print("Write the full part of the result.")
        print("Result=number1{}number2".format(operation))
        answer=int(input("result="))
        if(answer==result):
            print("+20 point")
            print("Congratulations {}, You know".format(username))
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter3+=1
        else : 
            print("-10 point")
            print("Sorry {}, you didn't know. True Answer=".format(username),result)
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter4+=1
    if(level==3):
        number1=randint(100,1000)
        number2=randint(100,1000)
        print("number1=",number1)
        print("number2=",number2)
        if(number1<50):
            operation="-" 
            result=number1-number2
        if(number1>49 and number1<100):
            operation="+"
            result=number1+number2
        if(number1>99 and number1<500):
            operation="*"
            result=number1*number2
        if(number1>499 and number1<1001):
            operation="//"
            result=number1//number2
            print("Write the full part of the result.")
        print("result=number1{}number2".format(operation))
        answer=int(input("result="))
        if(answer==result):
            print("+30 point")
            print("Congratulations {}, You know".format(username))
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter5+=1
        else : 
            print("-15 point")
            print("Sorry {}, you didn't know. True Answer=".format(username),result)
            command="0"
            print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
            command=input("Command=> ")
            while(command!="y" and command!="n"):
                print("You entered the wrong command. Re-enter the command.")
                print("Press the 'y' key to start or continue the game. Press the 'n' key to end the game.")
                command=input("Command=> ")
            if(command=="n"):
                print("Game Over {}!".format(username))
            counter6+=1
TotalScore = (counter1*(10)) + (counter2*(-5)) + (counter3*(20)) + (counter4*(-10)) + (counter5*(30)) + (counter6*(-15))
print("Total Score=",TotalScore)









